### ISSUE TITLE
Can't merge GAU and GAUC back into ERG

### ISSUE THREAD

**Issue by seby92** [DjedAlliance/Gluon-Ergo-WebUI#37]
Dispite I have enough of both tokens, i can't use fusion. The max amount is the same as the actual wallet balance.

![11](https://github.com/user-attachments/assets/3593e01a-7eeb-48cf-af8f-b30ddc585215)

This is the max I can fuse.

![22](https://github.com/user-attachments/assets/0d5259fa-9ead-403d-954d-aa43e566da5b)

**Comment by ceilican** [comment]
Thanks for reporting this! @sangeetparashar fixed this a few days ago.
